[package]
name = "merkle-trie"
version = "0.1.0"
edition = "2024"

[dependencies]
allocator-api2 = "0.4.0"
digest = "0.11.3"
tracing = { version = "0.1.44", features = ["release_max_level_info"] }

[dev-dependencies]
sha2 = "0.11.0"
test-log = { version = "0.2.20", features = ["color", "log", "trace"] }

[features]
std_allocator_api = []
